name: Java CI with Maven and Cucumber

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean verify

      - name: Run Cucumber tests
        run: mvn test

      - name: Generate Cucumber reports
        run: mvn verify

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/cucumber-reports

      - name: Deploy report page to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target