name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'  # Add the distribution input

      - name: Build with Maven
        run: mvn clean verify -Dtestng.dtd.http=true
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}

      - name: Run Cucumber Tests
        run: mvn test -Dcucumber.options="--plugin json:target/cucumber.json"
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}

      - name: Generate Cucumber Report
        uses: deblockt/cucumber-report-annotations-action@v1.8
        with:
          access-token: ${{ secrets.Token }}
          path: "**/target/cucumber.json"

      - name: Deploy report page to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.Token }}
          publish_dir: ./target